# Generated by Django 4.2.1 on 2023-07-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(default=None, max_length=10)),
                ('branches', models.PositiveIntegerField(default=1)),
                ('date_of_operation', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('minimum_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_lower_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_upper_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_payout_freq', models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('BA', 'Biannually'), ('A', 'Annually'), ('MA', 'Maturity')], max_length=2)),
                ('earning_per_1000_lower_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('earning_per_1000_upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premature_encashment', models.CharField(max_length=100)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bank')),
            ],
        ),
    ]
