# Generated by Django 4.2.1 on 2023-05-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('branches', models.PositiveIntegerField()),
                ('date_of_operation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indicative_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_payout_freq', models.PositiveIntegerField()),
                ('earning_per_1000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premature_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bank')),
            ],
        ),
    ]
