# Generated by Django 4.2.1 on 2023-11-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('rating_short_term', models.CharField(max_length=10)),
                ('rating_long_term', models.CharField(max_length=10)),
                ('choice_field', models.CharField(choices=[('short_term', 'Short Notice Term Deposit Certificate'), ('one_month', 'One Month Deposite Certificate'), ('three_month', 'Three Months Term Deposite Certificate'), ('six_month', 'Six Months Term Deposite Certificate'), ('one_year', 'One Year Term Deposite Certificate'), ('three_year', 'Three Year Term Deposite Certificate'), ('five_year', 'Five Year Term Deposite Certificate'), ('month_quarter_half', 'Monthly / Quaterly / Half Yearly Term Deposite Certificate'), ('ten_year', 'Ten Year Term Deposite Certificate'), ('recurring', 'Monthly Recurring Deposite Certificate')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_length', models.CharField(max_length=100)),
                ('profit_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payout_frequency', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankproduct')),
            ],
        ),
    ]
