# Generated by Django 4.2.1 on 2023-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bankproduct_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankproduct',
            name='choice_field',
        ),
        migrations.AddField(
            model_name='investment',
            name='choice_field',
            field=models.CharField(choices=[('short_term', 'Short Notice Term Deposit Certificate'), ('one_month', 'One Month Deposite Certificate'), ('three_month', 'Three Months Term Deposite Certificate'), ('six_month', 'Six Months Term Deposite Certificate'), ('one_year', 'One Year Term Deposite Certificate'), ('three_year', 'Three Year Term Deposite Certificate'), ('five_year', 'Five Year Term Deposite Certificate'), ('month_quarter_half', 'Monthly / Quaterly / Half Yearly Term Deposite Certificate'), ('ten_year', 'Ten Year Term Deposite Certificate'), ('recurring', 'Monthly Recurring Deposite Certificate')], default=('short_term', 'Short Notice Term Deposit Certificate'), max_length=50),
        ),
    ]
