# Generated by Django 4.2.1 on 2023-05-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_bank_branches_alter_bank_date_of_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit_payout_freq',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('BA', 'Biannually'), ('A', 'Annually')], max_length=2),
        ),
    ]
