# Generated by Django 4.2.1 on 2023-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_bankproduct_choice_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankproduct',
            name='bank_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
