# Generated by Django 4.2.1 on 2023-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_bankproduct_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='profit_rate',
            field=models.CharField(max_length=100),
        ),
    ]
