# Generated by Django 4.2.1 on 2023-11-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_investment_max_investment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankproduct',
            name='rating_long_term',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='rating_short_term',
        ),
        migrations.AddField(
            model_name='investment',
            name='rating_long_term',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='rating_short_term',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
