# Generated by Django 4.2.1 on 2023-12-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_remove_bankproduct_rating_long_term_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeInsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('min_eligibility_age', models.IntegerField()),
                ('max_eligibility_age', models.IntegerField()),
                ('max_maturity_age', models.BooleanField(default=False)),
                ('minimum_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_length', models.CharField(blank=True, max_length=100, null=True)),
                ('min_policy_term', models.IntegerField()),
                ('max_policy_term', models.IntegerField()),
                ('contribution_allocation', models.IntegerField()),
                ('premium_frequency', models.CharField(choices=[('yearly', 'Yearly'), ('half_yearly', 'Half Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], max_length=20)),
                ('loan_against_premium_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('free_look_up_period', models.CharField(blank=True, max_length=10, null=True)),
                ('partial_full_withdrawal', models.CharField(blank=True, max_length=10, null=True)),
                ('inflation_protection', models.CharField(max_length=100)),
                ('charges', models.CharField(blank=True, max_length=255, null=True)),
                ('bonus_allocation', models.CharField(blank=True, max_length=100, null=True)),
                ('product_benefit_1', models.CharField(blank=True, max_length=100, null=True)),
                ('product_benefit_2', models.CharField(blank=True, max_length=100, null=True)),
                ('product_benefit_3', models.CharField(blank=True, max_length=100, null=True)),
                ('product_benefit_4', models.CharField(blank=True, max_length=100, null=True)),
                ('product_benefit_5', models.CharField(blank=True, max_length=100, null=True)),
                ('product_benefit_6', models.CharField(blank=True, max_length=100, null=True)),
                ('product_benefit_7', models.CharField(blank=True, max_length=100, null=True)),
                ('optional_benefits', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.lifeinsurancecompany')),
            ],
        ),
    ]
