# Generated by Django 4.2.1 on 2023-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_lifeinsurancecompany_insuranceproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='max_policy_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='min_policy_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
