# Generated by Django 4.2.1 on 2023-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_alter_insuranceproduct_max_policy_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='contribution_allocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='inflation_protection',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='partial_full_withdrawal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
