# Generated by Django 4.2.1 on 2023-12-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionalFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_management_company', models.CharField(max_length=100)),
                ('subsidiary_of', models.CharField(max_length=100)),
                ('fund_name', models.CharField(max_length=100)),
                ('fund_type', models.CharField(max_length=50)),
                ('launch_date', models.DateField()),
                ('fund_size', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=10)),
                ('risk', models.CharField(max_length=50)),
                ('minimum_investment_in_pkr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('performance_past_3_years', models.CharField(max_length=100)),
                ('ytd_as_of_date', models.JSONField()),
                ('front_back_end_loading_fee', models.CharField(max_length=50)),
                ('management_fee', models.CharField(max_length=50)),
            ],
        ),
    ]
