# Generated by Django 4.2.1 on 2023-12-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_conventionalfund'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConventionalFund',
            new_name='IslamicFund',
        ),
    ]
