# Generated by Django 4.2.1 on 2023-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_rename_conventionalfund_islamicfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicfund',
            name='minimum_investment_in_pkr',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
