# Generated by Django 4.2.1 on 2023-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_alter_islamicfund_minimum_investment_in_pkr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicfund',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
