# Generated by Django 4.2.1 on 2023-12-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0016_alter_islamicfund_launch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionalFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_management_company', models.CharField(max_length=100)),
                ('subsidiary_of', models.CharField(blank=True, max_length=100, null=True)),
                ('fund_name', models.CharField(max_length=100)),
                ('fund_type', models.CharField(max_length=50)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('fund_size', models.CharField(max_length=20)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('risk', models.CharField(max_length=50)),
                ('minimum_investment_in_pkr', models.CharField(max_length=50)),
                ('performance_past_3_years', models.CharField(blank=True, max_length=100, null=True)),
                ('ytd_as_of_date', models.JSONField(default=dict)),
                ('front_back_end_loading_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('management_fee', models.CharField(max_length=50)),
            ],
        ),
    ]
