# Generated by Django 4.2.1 on 2024-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0017_conventionalfund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Term Deposit', 'verbose_name_plural': 'Term Deposits'},
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], default='local', max_length=50),
        ),
    ]
