# Generated by Django 4.2.1 on 2024-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0018_alter_investment_options_investment_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_images/'),
        ),
    ]
