# Generated by Django 4.2.1 on 2024-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0019_bank_bank_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='bank_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_images/'),
        ),
    ]
