# Generated by Django 4.2.1 on 2024-06-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0020_bankproduct_bank_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeinsurancecompany',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
