# Generated by Django 4.2.1 on 2024-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0021_lifeinsurancecompany_company_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conventionalfund',
            old_name='performance_past_3_years',
            new_name='return_field',
        ),
        migrations.RenameField(
            model_name='islamicfund',
            old_name='performance_past_3_years',
            new_name='benchmark',
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='back_end_load',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='benchmark',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='easy_redemption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='features',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='front_end_load',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='max_preservation_of_capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='no_lock_in_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='objective',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='pricing',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='retain_for_24_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='systematic_investment_plan_facility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='tax_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='tenor_period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='back_end_load',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='easy_redemption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='features',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='front_end_load',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='max_preservation_of_capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='no_lock_in_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='objective',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='performance',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='pricing',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='retain_for_24_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='return_field',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='systematic_investment_plan_facility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='tax_benefits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='islamicfund',
            name='tenor_period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
