# Generated by Django 4.2.1 on 2024-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0022_rename_performance_past_3_years_conventionalfund_return_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='max_maturity_age',
            field=models.IntegerField(),
        ),
    ]
