# Generated by Django 4.2.1 on 2024-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0023_insuranceproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='choice_field',
            field=models.CharField(choices=[('short_term', 'Short Notice Term Deposit Certificate'), ('one_month', 'One Month Deposite Certificate'), ('three_month', 'Three Months Term Deposite Certificate'), ('six_month', 'Six Months Term Deposite Certificate'), ('one_year', 'One Year Term Deposite Certificate'), ('three_year', 'Three Year Term Deposite Certificate'), ('five_year', 'Five Year Term Deposite Certificate'), ('month_quarter_half', 'Monthly / Quaterly / Half Yearly Term Deposite Certificate'), ('ten_year', 'Ten Year Term Deposite Certificate'), ('recurring', 'Monthly Recurring Deposite Certificate')], default='short_term', max_length=50),
        ),
    ]
