# Generated by Django 4.2.1 on 2024-12-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0025_alter_investment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='max_investment_type',
            field=models.CharField(choices=[('mention_amount', 'Mention the Amount'), ('no_limit', 'No Limit'), ('amount_above', 'Amount in Figure & Above')], default='mention_amount', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='choice_field',
            field=models.CharField(choices=[('short_term', 'Short Notice Term Deposit Certificate'), ('one_month', 'One Month Deposit Certificate'), ('three_month', 'Three Months Term Deposit Certificate'), ('six_month', 'Six Months Term Deposit Certificate'), ('one_year', 'One Year Term Deposit Certificate'), ('three_year', 'Three Year Term Deposit Certificate'), ('five_year', 'Five Year Term Deposit Certificate'), ('month_quarter_half', 'Monthly / Quaterly / Half Yearly Term Deposit Certificate'), ('ten_year', 'Ten Year Term Deposit Certificate'), ('recurring', 'Monthly Recurring Deposit Certificate')], default='short_term', max_length=50),
        ),
        migrations.AlterField(
            model_name='investment',
            name='max_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
