# Generated by Django 4.2.1 on 2024-12-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0026_investment_max_investment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.CharField(blank=True, choices=[('PKR', 'Pakistani Rupee'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal')], max_length=3, null=True),
        ),
    ]
