# Generated by Django 4.2.1 on 2024-12-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0027_alter_investment_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='max_investment_type',
        ),
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.CharField(blank=True, choices=[('PKR', 'PKR'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('AED', 'AED'), ('SAR', 'SAR')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='max_investment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='min_investment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
