# Generated by Django 4.2.1 on 2025-01-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0028_remove_investment_max_investment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='profit_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
