# Generated by Django 4.2.1 on 2025-01-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0029_alter_investment_profit_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='profit_rate',
            field=models.FloatField(),
        ),
    ]
