# Generated by Django 4.2.1 on 2025-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0030_alter_investment_profit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_expected_profit_rate',
            field=models.BooleanField(default=False),
        ),
    ]
