# Generated by Django 4.2.1 on 2025-01-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0033_remove_islamicfund_benchmark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islamicfund',
            old_name='back_end_load',
            new_name='front_back_end_load',
        ),
        migrations.RemoveField(
            model_name='islamicfund',
            name='front_end_load',
        ),
    ]
