# Generated by Django 4.2.1 on 2025-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0034_rename_back_end_load_islamicfund_front_back_end_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicfund',
            name='asset_management_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
