# Generated by Django 4.2.1 on 2025-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0035_alter_islamicfund_asset_management_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicfund',
            name='front_back_end_load',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='fund_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='fund_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='fund_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='management_fee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='minimum_investment_in_pkr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='return_field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='risk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='islamicfund',
            name='subsidiary_of',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
