# Generated by Django 4.2.1 on 2025-01-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0036_alter_islamicfund_front_back_end_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicfund',
            name='performance',
            field=models.TextField(null=True),
        ),
    ]
