# Generated by Django 4.2.1 on 2025-01-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0037_alter_islamicfund_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicfund',
            name='launch_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
