# Generated by Django 4.2.1 on 2025-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0038_alter_islamicfund_launch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventionalfund',
            name='back_end_load',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='benchmark',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='category',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='easy_redemption',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='features',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='front_back_end_loading_fee',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='front_end_load',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='max_preservation_of_capital',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='no_lock_in_period',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='retain_for_24_months',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='systematic_investment_plan_facility',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='tax_benefits',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='tenor_period',
        ),
        migrations.RemoveField(
            model_name='conventionalfund',
            name='ytd_as_of_date',
        ),
        migrations.AddField(
            model_name='conventionalfund',
            name='front_back_end_load',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='asset_management_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='fund_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='fund_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='fund_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='launch_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='management_fee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='minimum_investment_in_pkr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='performance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='return_field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='risk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conventionalfund',
            name='subsidiary_of',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
