# Generated by Django 4.2.1 on 2025-01-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0039_remove_conventionalfund_back_end_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='previews/'),
        ),
    ]
