# Generated by Django 4.2.1 on 2025-01-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0040_alter_article_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(upload_to='previews/'),
        ),
    ]
