# Generated by Django 4.2.1 on 2025-01-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0041_alter_article_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='is_expected_profit_rate',
        ),
    ]
