# Generated by Django 4.2.1 on 2025-01-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0042_remove_investment_is_expected_profit_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conventionalfund',
            old_name='return_field',
            new_name='ytd_as_of_date',
        ),
        migrations.RenameField(
            model_name='islamicfund',
            old_name='return_field',
            new_name='ytd_as_of_date',
        ),
    ]
