# Generated by Django 4.2.1 on 2025-01-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0043_rename_return_field_conventionalfund_ytd_as_of_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conventionalfund',
            old_name='ytd_as_of_date',
            new_name='ytd_as_of',
        ),
        migrations.RenameField(
            model_name='islamicfund',
            old_name='ytd_as_of_date',
            new_name='ytd_as_of',
        ),
    ]
