# Generated by Django 4.2.1 on 2025-01-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0044_rename_ytd_as_of_date_conventionalfund_ytd_as_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.lifeinsurancecompany'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='max_eligibility_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='max_maturity_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='min_eligibility_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='minimum_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='premium_frequency',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('half_yearly', 'Half Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
    ]
