# Generated by Django 4.2.1 on 2025-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0045_alter_insuranceproduct_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='optional_benefits',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_benefit_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_benefit_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_benefit_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_benefit_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_benefit_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_benefit_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_benefit_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='product_length',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
