# Generated by Django 4.2.1 on 2025-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0046_alter_insuranceproduct_optional_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='max_eligibility_age',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='max_maturity_age',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='min_eligibility_age',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='minimum_premium',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
