# Generated by Django 4.2.1 on 2025-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0048_alter_investment_max_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='choice_field',
            field=models.CharField(choices=[('short_term', 'Short Notice Term Deposit Certificate'), ('one_month', 'One Month Deposit Certificate'), ('three_month', 'Three Months Term Deposit Certificate'), ('six_month', 'Six Months Term Deposit Certificate'), ('one_year', 'One Year Term Deposit Certificate'), ('three_year', 'Three Year Term Deposit Certificate'), ('five_year', 'Five Year Term Deposit Certificate'), ('month_quarter_half', 'Monthly / Quaterly / Half Yearly Term Deposit Certificate'), ('ten_year', 'Ten Year Term Deposit Certificate'), ('recurring', 'Monthly Recurring Deposit Certificate'), ('mahana_profit', 'Mahana Profit')], default='short_term', max_length=50),
        ),
    ]
